#!/usr/bin/env sh

while true; do
    is-day 53.5 -10
    sleep 15
done | while read state; do
    case $state in
        day|night) ;;
        sunset) brownout +2;;
        dusk) brownout +5;;
        dawn) brownout -2;;
        sunrise) brownout -5;;
    esac
done
